### ISSUE TITLE
Global `d2 style js apply` sometimes doesn't work...

### ISSUE THREAD

**Issue by amcgee** [dhis2/cli-style#216]
In some situations, running `d2 style js apply` (the global version) loops through all the files correctly but doesn't actually change any files.  It says simply `Formatted {x} javascript files` (side note - confusing messages, the files were already formatted so the tool didn't actually format them) and no files change.

Running `./node_modules/d2-style js apply` appears to work more consistently, although running it from a `package.json` script like so (`"format": "d2-style js apply || d2-style text apply"`) seems to have the same issue.

I reproduced this when cloning [dhis2/analytics](https://github.com/dhis2/analytics) in a clean environment (new laptop) and haven't yet found a way to get it working in that environment.

**Comment by varl** [comment]
@amcgee Could you try to upgrade to 6.0.0 in https://github.com/dhis2/analytics/blob/master/package.json#L38?

The log messages and the way formatting runs internal has changed.

**Comment by varl** [comment]
I think that this bug is due to the fact that we install it with `yarn global add @dhis2/cli`, but then internally we use `npx` to find and execute the commands, so it cannot find the tools like `prettier` and `eslint` where it expects it.

**Comment by varl** [comment]
Resolved in 7.2.0.
