### ISSUE TITLE
Js check fails without clarifying what went wrong

### ISSUE THREAD

**Issue by ismay** [dhis2/cli-style#22]
In trying out the cli-style lib and checking js, the check failed with the following error:

<img width="403" alt="screenshot 2019-03-06 at 16 56 00" src="https://user-images.githubusercontent.com/7355199/53894719-e1a7f700-4030-11e9-8e13-7c76222544bd.png">

To me as a user it is unclear what failed here. Knowing that it runs prettier I'm assuming that's what it is, but getting feedback on that it _is_ prettier that failed for example, would clarify to me what went wrong exactly.

**Comment by varl** [comment]
That error just means that there are files which do not comply to the code style.

Maybe we can drop the scary error message and just list the files that do not comply to the standard.

**Comment by varl** [comment]
```
./bin/d2-style js check /home/varl/dev/dhis2/libs/codemods/d2/v31.1.0/change-imports.js

1 file(s) needs to be formatted: 
../codemods/d2/v31.1.0/change-imports.js
```
