### ISSUE TITLE
on the documentation regarding migration adding the dependency is not marked as --dev

### ISSUE THREAD

**Issue by paschalidi** [dhis2/cli-style#233]
Hello y'all and good day! 

While reading the documentation and specifically the [migration guide](https://cli-style.dhis2.nu/#/migrate-guide) I could see that in step 5 we are asking the user to install the package. 
In my understanding the package could be a dev dependency. Am I getting this right? 

I am happy to open a PR to resolve this issue. Simply give me the green light for it! 👍

**Comment by amcgee** [comment]
@paschalidi that's correct, I think this should be recommended as a `dev` dependency.  For small documentation changes like this please feel free to open a PR directly, no need to have an issue first unless it's non-trivial to make the change

**Comment by paschalidi** [comment]
Okay that makes sense. For small changes like this I will be opening a PR straight on you are right :)

**Comment by amcgee** [comment]
Great - thanks for raising the docs issues by the way, very much appreciated 🙂

**Comment by paschalidi** [comment]
Happy to help a little bit to improve the good work you all done here!
