### ISSUE TITLE
Initialisation throws error: Cannot find module 'eslint-plugin-prettier'

### ISSUE THREAD

**Issue by paschalidi** [dhis2/cli-style#234]
Hello y'all. 👋 

I gave a shot to install the package to the [capture-app](https://github.com/dhis2/capture-app) just to see how it would look after applying the new styles. However I got into the problem that `eslint` wont work as expected. It would throw an error like similar to this when I execute the recommended  command `"format": "yarn format:js && yarn format:text"`

<details>
<summary>Click here to see terminal debug info</summary>
<pre>
Failed to load plugin 'prettier' declared in '.eslintrc.js » /Users/username/dev/capture-app/node_modules/@dhis2/cli-style/config/js/eslint-react.config.js » ./eslint.config.js': Cannot find module 'eslint-plugin-prettier'
Require stack:
- /Users/username/dev/capture-app/__placeholder__.js
</pre>
</details>

Because I found this weird I thought of installing the package to a fresh `create-react-app` repository. I have to say that this worked without any errors. 

Then I thought that one of the existing packages of the `capture-app` is probably what is causing the issue. So I hunted down the package and ended up to `"react-scripts": "3.0.1"` that we are using currently. 

I dont know if we wanna be supporting that version since updating `react-scripts` to the latest version fixes the problem. In any case I thought it would be interesting for the maintainers to know this is why I am opening this issue. Please feel free to just close it if you find it irrelevant.

**Comment by amcgee** [comment]
Hi @paschalidi - are you using `yarn` >= 1.20 by chance?  There are some dependendency hoisting regressions in the latest yarn so we recommend using `yarn@1.19.1`

**Comment by amcgee** [comment]
There shouldn't be any implicit dependencies between `@dhis2/cli-style` and `react-script`, they should operate completely independently.  I imagine this is an issue with package hoisting.

**Comment by paschalidi** [comment]
My version of `yarn` is 1.22.4.  I could try to change the version to the one that is recommended and see how this goes. Will update here with a comment @amcgee

**Comment by paschalidi** [comment]
@amcgee I set the version of `yarn` to `1.19.1` that you recommended. For the records you do that with `yarn set version 1.19.1`

Still the same error. And still the problem disappears when I update `react-scripts` to the latest `3.4.1`

Check this out I made a sample repo where you could also see that. https://github.com/paschalidi/cli-config-from-dhis2

Runnig `yarn format` will give you the error

**Comment by varl** [comment]
Getting the same problem with the `alpha` and it's indeed because of hoisting.

Everything that gets hoisted to `node_modules/` works fine, but if there's a unique dep, `node_modules/@dhis2/cli-style/node_modules/eslint-plugin-import` Yarn will not hoist that.

A bit surprising, will see if I can come up with a fix.

**Comment by varl** [comment]
The `alpha` should fix this problem.

**Comment by amcgee** [comment]
Just cross-posting here - https://github.com/atlassian/yarn-deduplicate might help with spot-fixing dependency hoisting issues

**Comment by paschalidi** [comment]
This is solved for me now. 

The solution was basically that we moved to app platform.
