### ISSUE TITLE
"No files to style" message

### ISSUE THREAD

**Issue by ismay** [dhis2/cli-style#24]
The feedback I get when I check all my files:

<img width="394" alt="screenshot 2019-03-06 at 17 26 14" src="https://user-images.githubusercontent.com/7355199/53896984-77de1c00-4035-11e9-9336-b89732e1d564.png">

Might lead one to believe that you didn't pass any files. When I'm assuming that this is meant to indicate that all checked files are ok. Or am I wrong in assuming that? I was expecting `--all` to check all js in the project.

**Comment by varl** [comment]
It means all files are according to standard. I see how that message is a bit shite...
