### ISSUE TITLE
Fix the no-unused-modules ignored files syntax

### ISSUE THREAD

**Issue by ismay** [dhis2/cli-style#248]
See the slack discussion here: https://dhis2.slack.com/archives/CHENB0272/p1588154127084500

It seems that the `ignoreExports` option I was using is not the correct option for ignoring files completely for this rule. Instead it seems like https://github.com/benmosher/eslint-plugin-import#importignore is the one we need.

See if moving to that option would fix the error @varl was seeing.

**Comment by varl** [comment]
Looks like this may be related: https://github.com/benmosher/eslint-plugin-import/issues/1659

**Comment by varl** [comment]
Seems like the workaround is to specify it in the local configuration for our repos for now and leave it untouched in the main config.

**Comment by ismay** [comment]
Ah yeah 👍
