### ISSUE TITLE
Does not prevent re-committing after problems are fixed (but not staged)

### ISSUE THREAD

**Issue by Birkbjo** [dhis2/cli-style#253]
When committing something that fails es-lint the pre-commit will fail. However, if you fix the problems in your file(s) but don't stage them, you will be able to commit the files with the problems present.

There's been times where I've forgotten to re-stage the fixed files, which has resulted in committed files that actually does not pass the style-checks. This is rather confusing when you work in that file later and you get style-errors for code you haven't touched.

I asked Viktor briefly about this some time ago, and I believe it's because we don't want to stash the changes and run only on staged files?

**Comment by varl** [comment]
While being able to accidentally commit style errors is not ideal, we check the code for lint again on GitHub Actions on the PR, so the PR will be blocked from merging until the style issues have been resolved.

Using the scope `style:` is the appropriate commit message subject in this case.

**Comment by varl** [comment]
Superseded by: https://jira.dhis2.org/browse/CLI-6
