### ISSUE TITLE
Warn for untranslated strings

### ISSUE THREAD

**Issue by ismay** [dhis2/cli-style#256]
@martinkrulltott rightfully noted that it'd be nice to detect untranslated strings. I've found a couple of useful rules that we could maybe add to cli-style for that purpose:

- https://www.npmjs.com/package/eslint-plugin-i18next
- https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-literals.md

The first seems closest to what we want. Seems good to enable this as a warning, so that it's easy to see at a glance where there are untranslated strings in an app, but doesn't break a build.

See: https://dhis2.slack.com/archives/C0BP0RABF/p1589895857107300

**Comment by amcgee** [comment]
Related to dhis2/app-platform#369

**Comment by varl** [comment]
Superseded by: https://jira.dhis2.org/browse/CLI-5
