### ISSUE TITLE
Rename whitelist/blacklist to includeList/ignoreList

### ISSUE THREAD

**Issue by varl** [dhis2/cli-style#264]
It's just better, all around.

https://github.com/dhis2/cli-style/blob/master/src/utils/files.js#L10-L28

**Comment by jenniferarnesen** [comment]
Hmm, looking at the content of those lists, they look almost more like `includeList` and `ignoreList`?  Or maybe I'm missing some context...

**Comment by varl** [comment]
I don't think you are missing context, that's the intent. :+1:
