### ISSUE TITLE
Cli-style trying to lint a deleted file

### ISSUE THREAD

**Issue by ismay** [dhis2/cli-style#43]
It seems like cli-style is trying to get eslint to process a deleted file:

<img width="575" alt="Screenshot 2019-05-14 at 10 29 44" src="https://user-images.githubusercontent.com/7355199/57684900-04f5b080-7637-11e9-80c3-ded3a4369372.png">

<img width="1280" alt="Screenshot 2019-05-14 at 10 29 23" src="https://user-images.githubusercontent.com/7355199/57684911-0c1cbe80-7637-11e9-9007-9b76644cd8b1.png">

I was thinking, a couple of the bugs I've run into have had to do with this area of cli-style, and lint-staged already deals with running tasks on staged files really well. Would it not be easier to use lint-staged for this area of cli-style? Not sure how exactly it would fit into cli-style, but if it could, it would save us time.

**Comment by varl** [comment]
Maybe lint-staged makes sense at some point, but to fix this it's just a matter of including `--diff-filter=d` to exclude deleted files from the diff listing.

**Comment by ismay** [comment]
Ok cool, sounds good, thanks! 👍
